language: php

services:
  - mysql

php:
  - 5.6.12

before_script:
  - mysql -e 'create database travis_test;'
  - cp .env.test .env
  - php artisan key:generate
  - php artisan migrate
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
